### ISSUE TITLE
Allow cross-origin image loading

### ISSUE THREAD

**Issue by james090500** [yushijinhun/skinview-utils#6]
Attempting to load an image with SkinViewer3D fails due to CORS.

I believe https://github.com/bs-community/skinview-utils/blob/master/src/load-image.ts#L13 should have a 
```
image.crossOrigin = "Anonymous";
```

![image](https://user-images.githubusercontent.com/20372645/87256061-a1a81e00-c487-11ea-9cb0-c3f13b3f61f0.png)

**Comment by yushijinhun** [comment]
Sorry for my mistake. I had fixed this bug before in https://github.com/bs-community/skinview-utils/commit/395f34900bbfb24678c0a260bbf063686ab6b480, but forgot to update the `master` branch.

The fix is available in v0.5.5, which was released about half a month ago. Though the `master` branch fell behind, npm & git tag are up-to-date.

**Comment by james090500** [comment]
This is still an issue though. Especial on SkinViewer3D. When doing 
```
skinViewer.loadSkin("https://crafatar.com/skins/ba4161c03a42496c8ae07d13372f3371")
```

The typeof source is a "string" so the crossOrigin code is never reached.

**Comment by yushijinhun** [comment]
@james090500 Thanks! I even didn't notice that.

**Comment by james090500** [comment]
Awesome! Will this update get pushed to NPM so Skinview3D will recieve the update?

**Comment by yushijinhun** [comment]
I published skinview-utils v0.5.6 just now. skinview3d will have an alpha release soon.

**Comment by james090500** [comment]
Thank you
